In [2]:
import requests

In [15]:
url = "https://api.worldbank.org/v2/country/KE/indicator/DT.DOD.DECT.CD?format=json"

params = {
    'date': '2010:2024'
}
response = requests.get(url, params=params)
response.status_code

200

In [17]:
data = response.json()
data

[{'page': 1,
  'pages': 1,
  'per_page': 50,
  'total': 15,
  'sourceid': '2',
  'lastupdated': '2025-06-05'},
 [{'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2024',
   'value': None,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2023',
   'value': 42910026054.2,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2022',
   'value': 41556299639.8,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2021',
   'value': 41219100011.5,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2020',
   'value': 38038451074.1,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2019',
   'value': 34970099589.9,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2018',
   'value': 31433802015.7,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2017',
   'value': 26951349499.4,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2016',
   'value': 21057671043.3,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2015',
   'value': 19783760501.7,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2014',
   'value': 16911742536.7,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2013',
   'value': 13775500738.7,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2012',
   'value': 11832175543.2,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2011',
   'value': 10042095566.4,
   'unit': '',
   'obs_status': '',
   'decimal': 0},
  {'indicator': {'id': 'DT.DOD.DECT.CD',
    'value': 'External debt stocks, total (DOD, current US$)'},
   'country': {'id': 'KE', 'value': 'Kenya'},
   'countryiso3code': 'KEN',
   'date': '2010',
   'value': 8885235532.9,
   'unit': '',
   'obs_status': '',
   'decimal': 0}]]

In [26]:
import pandas as pd

In [ ]:
rel_data = []

for item in data[1]:
    rel_data.append({
        'country_code' : item['country']['id'],
        'debt_value' : item['value'],
        'year' : int(item['date']),
        'debt_desc' : item['indicator']['value']
    })


df = pd.DataFrame(rel_data)
df.dropna(inplace=True)
df

,country_code,debt_value,year,debt_desc
1,KE,4.291003e+10,2023,"External debt stocks, total (DOD, current US$)"
2,KE,4.155630e+10,2022,"External debt stocks, total (DOD, current US$)"
3,KE,4.121910e+10,2021,"External debt stocks, total (DOD, current US$)"
4,KE,3.803845e+10,2020,"External debt stocks, total (DOD, current US$)"
5,KE,3.497010e+10,2019,"External debt stocks, total (DOD, current US$)"
6,KE,3.143380e+10,2018,"External debt stocks, total (DOD, current US$)"
7,KE,2.695135e+10,2017,"External debt stocks, total (DOD, current US$)"
8,KE,2.105767e+10,2016,"External debt stocks, total (DOD, current US$)"
9,KE,1.978376e+10,2015,"External debt stocks, total (DOD, current US$)"
10,KE,1.691174e+10,2014,"External debt stocks, total (DOD, current US$)"
11,KE,1.377550e+10,2013,"External debt stocks, total (DOD, current US$)"
12,KE,1.183218e+10,2012,"External debt stocks, total (DOD, current US$)"
13,KE,1.004210e+10,2011,"External debt stocks, total (DOD, current US$)"
14,KE,8.885236e+09,2010,"External debt stocks, total (DOD, current US$)"

In [43]:
df.describe()

         debt_value       year
count  1.400000e+01    14.0000
mean   2.566909e+10  2016.5000
std    1.257976e+10     4.1833
min    8.885236e+09  2010.0000
25%    1.455956e+10  2013.2500
50%    2.400451e+10  2016.5000
75%    3.727136e+10  2019.7500
max    4.291003e+10  2023.0000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 1 to 14
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_code  14 non-null     object
 1   debt_value    14 non-null     float64
 2   year          14 non-null     int64
 3   debt_desc     14 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 560.0+ bytes

In [45]:
from sqlalchemy import create_engine

engine = create_engine(f"postgresql://avnadmin:AVNS_Jvib48pYtaFIOeAPq2z@my-postgres-db-navashub.f.aivencloud.com:12378/defaultdb?sslmode=require")


df.to_sql(
    'external_debt',
    engine,
    if_exists='replace',  
    index=False,
)

14